services:
  parser:
    build:
      context: ./
      dockerfile: ./parser.Dockerfile
    restart: always
    container_name: rockappapi_parser
    environment:
      - "PYTHONUNBUFFERED=1"
      - "API_URL=http://rockappapi_app:80"
      - "FROM_PAGE=49"
    networks:
      default:
    volumes:
      - rockappapi_parser_cache:/usr/src/app/cache

networks:
  default:
    name: rockappapi_network

volumes:
  rockappapi_parser_cache:
