"""add user

Revision ID: 2d9b683155f5
Revises: 9ffece019c2c
Create Date: 2025-05-26 16:43:44.720557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d9b683155f5'
down_revision: Union[str, None] = '9ffece019c2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_ranks',
    sa.Column('rocks_cost', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_ranks_pkey'))
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('app_bundle', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('avatar', sa.LargeBinary(), nullable=True),
    sa.Column('favorite_rock', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_foreign_key(op.f('rock_detections_user_id_fkey'), 'rock_detections', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('rock_detections_user_id_fkey'), 'rock_detections', type_='foreignkey')
    op.drop_table('users')
    op.drop_table('user_ranks')
    # ### end Alembic commands ###
