"""add rocks

Revision ID: 9ffece019c2c
Revises: 
Create Date: 2025-05-22 21:21:02.319823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ffece019c2c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rock_detections',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('app_bundle', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('detector_result', sa.String(), nullable=True),
    sa.Column('rock_id', sa.Uuid(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('rock_detections_pkey'))
    )
    op.create_index(op.f('rock_detections_id_idx'), 'rock_detections', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('rock_detections_id_idx'), table_name='rock_detections')
    op.drop_table('rock_detections')
    # ### end Alembic commands ###
