"""rename user rocks_cost

Revision ID: bfc72fec3922
Revises: 2d9b683155f5
Create Date: 2025-05-27 15:00:45.973007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfc72fec3922'
down_revision: Union[str, None] = '2d9b683155f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_ranks', sa.Column('rocks_count', sa.Integer(), nullable=False))
    op.drop_column('user_ranks', 'rocks_cost')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_ranks', sa.Column('rocks_cost', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('user_ranks', 'rocks_count')
    # ### end Alembic commands ###
